[[headers]]
for = "/*"
  [headers.values]
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Embedder-Policy = "require-corp"
  Cross-Origin-Resource-Policy = "same-origin"
  X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*.wasm"
  [headers.values]
  Content-Type = "application/wasm"
  Cache-Control = "public, max-age=31536000, immutable"
